version: "3.8"

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./app:/usr/src/app